### PR TITLE
Wrapper: Add error log when radspec evaluation fails

### LINKED ISSUE #101: Gracefully handle errors in Radspec
1. Ignore error and provide a default message
2. Log error to console
3. ???
4. Profit

### PR DESCRIPTION
**Pull request by gh1dra**
Fixes #101.

We could also take this opportunity to add tests to `describeTransaction` but I'm not sure where to put them so that they are aligned with the pattern. Also creating stubs for radspec could be additional work outside the scope of this small PR.

### CODE REVIEW

File: packages/aragon-wrapper/src/rpc/handlers/describe-transaction.js [hunk 1]
```diff
@@ -22,6 +22,10 @@ export default async function (request, proxy, wrapper) {
         description: processed.description
       }
     } catch (_) {}
+  } else {
+    return {
+      ...transaction
+    }
```
Comment (gh1dra) [inline packages/aragon-wrapper/src/rpc/handlers/describe-transaction.js]: Was trying to encapsulate the logic here: https://github.com/aragon/aragon.js/issues/101#issuecomment-418801302

Though this may not be needed, as if the `evaluatedNotice` is undefined, the `tryEvaluatingRadspec` method returns the fields inside the transaction as well: https://github.com/aragon/aragon.js/blob/1684b7696d48ed3e248ba1dc426e343dff5ed850/packages/aragon-wrapper/src/radspec/index.js#L52

Comment (sohkai) [reply packages/aragon-wrapper/src/rpc/handlers/describe-transaction.js]: Yes, this part isn't needed because we're only interested in returning the `description` or `annotatedDescription` in this API and not the entire transaction (it's already given as input).
